name: Verify Build

on:
    push:
        branches:
            - main
    pull_request:
    workflow_dispatch:

jobs:
    verification:
        name: Verification
        runs-on: ubuntu-latest
        steps:
            -   name: Check out project
                uses: actions/checkout@v4
            -   name: Set up JDK 11
                uses: actions/setup-java@v4
                with:
                    java-version: '11'
                    distribution: 'liberica'
            -   name: Setup Gradle
                uses: gradle/actions/setup-gradle@v4
                with:
                    develocity-access-key: ${{ secrets.DEVELOCITY_ACCESS_KEY }}
            -   name: Build and bundle plugin artifact
                run: ./gradlew clean build -Porg.gradle.java.installations.fromEnv=JAVA_HOME_11_X64 -PjavaCompilerVersion=11
                env:
                    DEVELOCITY_TEST_INSTANCE: ${{ secrets.DEVELOCITY_ACCESS_KEY != null && 'https://ge.solutions-team.gradle.com' || '' }}
