name: Create Development Release

on:
    workflow_run:
        workflows:
            - "Verify Build"
        types:
            - completed
        branches:
            - main
    workflow_dispatch:

permissions:
    contents: write

jobs:
    development_release:
        if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}
        name: Release
        runs-on: ubuntu-latest
        steps:
            -   name: Check out project
                uses: actions/checkout@v4
            -   name: Set up JDK 6
                uses: actions/setup-java@v4
                with:
                    java-version: '6.0.119'
                    distribution: 'zulu'
                    architecture: x64
            -   name: Set up JDK 11
                uses: actions/setup-java@v4
                with:
                    java-version: '11'
                    distribution: 'liberica'
            -   name: Setup Gradle
                uses: gradle/actions/setup-gradle@v4
                with:
                    develocity-access-key: ${{ secrets.DEVELOCITY_ACCESS_KEY }}
            -   name: Build and bundle plugin artifact
                run: ./gradlew clean build -Porg.gradle.java.installations.fromEnv=JAVA_HOME_6_0_119_X64 -PjavaCompilerVersion=6
                env:
                    DEVELOCITY_TEST_INSTANCE: https://ge.solutions-team.gradle.com
            -   name: Create GitHub release
                run: ./gradlew githubRelease
                env:
                    TEAMCITY_PLUGIN_GIT_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            -   name: Upload plugin artifact
                uses: actions/upload-artifact@v4
                with:
                    name: develocity-teamcity-plugin
                    path: build/distributions/develocity-teamcity-plugin-*.zip
